/* eslint-disable @typescript-eslint/no-inferrable-types */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Laravel
 * Joy VoyagerApi module adds REST Api end points to Voyager with Passport and Swagger support https://github.com/rxcod9/joy-voyager-api.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import {
  HttpClient,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse,
} from '@angular/common/http';
import { Inject, Injectable, Optional } from '@angular/core';
import { CustomHttpUrlEncodingCodec } from '../../encoder';

import { Observable } from 'rxjs';

import { Configuration } from '../../configuration';
import { BASE_PATH } from '../../variables';

@Injectable()
export abstract class AbstractOptionsDataService {
  protected httpClient: HttpClient;
  protected basePath = '/';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    this.httpClient = httpClient;
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * geo_infos index
   *
   * @param filters
   * @param q Global search
   * @param page
   * @param length
   * @param orderBy Sort by column
   * @param sortOrder Sort by direction
   * @param showSoftDeleted
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public itemsIndex(
    filters?: any,
    q?: any,
    page?: any,
    length?: any,
    orderBy?: any,
    sortOrder?: any,
    showSoftDeleted?: any,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<any>;
  public itemsIndex(
    filters?: any,
    q?: any,
    page?: any,
    length?: any,
    orderBy?: any,
    sortOrder?: any,
    showSoftDeleted?: any,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>;
  public itemsIndex(
    filters?: any,
    q?: any,
    page?: any,
    length?: any,
    orderBy?: any,
    sortOrder?: any,
    showSoftDeleted?: any,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>;
  public itemsIndex(
    filters?: any,
    q?: any,
    page?: any,
    length?: any,
    orderBy?: any,
    sortOrder?: any,
    showSoftDeleted?: any,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let queryParameters = new HttpParams({
      encoder: new CustomHttpUrlEncodingCodec(),
    });
    if (q !== undefined && q !== null) {
      queryParameters = queryParameters.set('q', <any>q);
    }
    if (page !== undefined && page !== null) {
      queryParameters = queryParameters.set('page', <any>page);
    }
    if (length !== undefined && length !== null) {
      queryParameters = queryParameters.set('length', <any>length);
    }
    if (orderBy !== undefined && orderBy !== null) {
      queryParameters = queryParameters.set('order_by', <any>orderBy);
    }
    if (sortOrder !== undefined && sortOrder !== null) {
      queryParameters = queryParameters.set('sort_order', <any>sortOrder);
    }
    if (showSoftDeleted !== undefined && showSoftDeleted !== null) {
      queryParameters = queryParameters.set(
        'showSoftDeleted',
        <any>showSoftDeleted
      );
    }

    Object.keys(filters ? filters : {}).forEach((key) => {
      if (filters[key] !== undefined && filters[key] !== null) {
        queryParameters = queryParameters.set(
          'filters[' + key + ']',
          <any>filters[key]
        );
      }
    });

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = [];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<any>(
      'get',
      `${this.basePath}/api/${this.getDomainNamePath()}`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  protected abstract getDomainNamePath(): string;
}
